version: 2.1

jobs:
  publish:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: |
            set -e

            VERSION=$(node -p "require('./package.json').version")
            PUBLISHED_VERSION=$(npm view @ministryofjustice/fb-deploy-utils version);

            if [ "$VERSION" != "$PUBLISHED_VERSION" ]
            then
              npm publish
            fi

workflows:
  commit-workflow:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
